name: lstm_stocks2
channels:
  - defaults
  - https://conda.anaconda.org/trax
dependencies:
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.1.5
  - pip=20.3.3
  - python=3.7.9
  - pytorch=1.7.1
  - scikit-learn=0.23.2
  - torchvision=0.4.2
  - pip:
    - mpl-finance==0.10.1
    - yfinance==0.1.55
